---
- name: My test playbook
  hosts: all
  become: true
  tasks:
   - name: installing httpd
     yum:
       name: httpd
       state: present

   - name: starting service
     service:
       name: httpd
       state: started
