---
- name: My test Playbook
  hosts: all
  become: true
  tasks:
    - name: Installing httpd
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Installing apache2
      apt:
        name: apache2
        state: installed
      when: ansible_os_family == "Debian"

    - name: Starting service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "Redhat"

    - name: Starting service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

